

const Screens = {
     BOTTOM_TAB_WRAPPER:"BOTTOM_TAB_WRAPPER",
     ALL_MOVIES_SCREEN:"ALL_MOVIES_SCREEN",
     ALL_TV_SCREENS:"ALL_TV_SCREENS",
     SINGLE_MOVIE_SCREEN:"SINGLE_MOVIE_SCREEN",
     SINGLE_TV_SHOW_SCREEN:"SINGLE_TV_SHOW_SCREEN",
     SEARCH_SCREEN:"SEARCH_SCREEN"

}

export default Screens
